# Generated by Django 4.2 on 2025-03-07 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_actividadsistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='ambiente',
            options={'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='competencia',
            options={'verbose_name': 'Competencia', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructores'},
        ),
        migrations.AlterModelOptions(
            name='programaformacion',
            options={'verbose_name': 'Programa de Formación', 'verbose_name_plural': 'Programas de Formación'},
        ),
        migrations.AddField(
            model_name='actividadsistema',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='competencias_imparte',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programaformacion',
            name='nombre_programa',
            field=models.CharField(max_length=100),
        ),
    ]
