# Generated by Django 4.2 on 2025-03-07 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('instructor', 'Instructor'), ('competencia', 'Competencia'), ('programa', 'Programa de Formación'), ('ambiente', 'Ambiente'), ('horario', 'Horario')], max_length=20)),
                ('accion', models.CharField(choices=[('crear', 'Creación'), ('editar', 'Edición'), ('eliminar', 'Eliminación'), ('generar', 'Generación')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('elemento_id', models.IntegerField(blank=True, null=True)),
                ('elemento_nombre', models.CharField(blank=True, max_length=255)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad del Sistema',
                'verbose_name_plural': 'Actividades del Sistema',
                'db_table': 'ActividadSistema',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
