# Generated by Django 4.2 on 2025-03-10 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_alter_administrador_options_alter_ambiente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadsistema',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='actividadsistema',
            name='leido',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Leído'),
        ),
        migrations.AddIndex(
            model_name='actividadsistema',
            index=models.Index(fields=['leido', 'fecha_hora'], name='ActividadSi_leido_61d87b_idx'),
        ),
    ]
